-- Frozen atomic evidence records from Claim Ledger v1.1.1 Sections 15.1 and 19.1.
-- This import preserves ledger findings, CMC, operational class, and score-effect wording.
-- Normalized score_effect remains NONE because these rows explicitly do not authorize
-- a claim-score change in v1.1.1.

BEGIN;

INSERT INTO evidence (
  evidence_id, source_id, population_id, design_class, intervention, sample_or_system,
  measured_variable, finding, operational_class, causal_manipulation, causal_manipulation_scope,
  preregistered, independent_replication, cmc, oec, evidence_status,
  ledger_score_effect_text, ledger_interpretation, ledger_version,
  source_artifact, source_locator, score_effect, provenance
) VALUES
('AN-001','SRC-015','ANESTHESIA','Within-subject anesthetic state comparison','Propofol, xenon, ketamine','Unresponsive healthy adults','TMS-EEG complexity','TMS-EEG complexity was low with propofol/xenon but remained compatible with conscious experience under ketamine; retrospective reports dissociated unresponsiveness from unconsciousness.','Perturbation + convergent report','TRUE','CONSCIOUSNESS_LINKED_SYSTEM','ND','ND','3','NA','VALIDATED','No automatic claim-score change; strengthens anesthesia as a high-CMC test measurement bed','IIT-1/IIT-4; state-level integration/complexity; cross-theory consciousness','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 15.1','NONE','{"import":"v1.1.1","source_table":"15.1 Anesthesia evidence register"}'::jsonb),
('AN-002','SRC-016','ANESTHESIA','Within-subject state transition observational fMRI','Graded propofol sedation, loss, recovery','Humans under graded propofol','Higher-order frontoparietal and thalamocortical connectivity','Higher-order frontoparietal and thalamocortical connectivity decreased with loss of consciousness while lower sensory networks were relatively preserved.','Within-subject state transition, observational fMRI','FALSE','NONE','ND','ND','2','NA','VALIDATED','Supports consciousness-adjacent network claims; not unique to GNWT','GNW-1/GNW-2; access architecture; PP/RPT indirect','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 15.1','NONE','{"import":"v1.1.1","source_table":"15.1 Anesthesia evidence register"}'::jsonb),
('AN-003','SRC-017','ANESTHESIA','Simultaneous EEG-fMRI directional connectivity','Propofol loss of consciousness','Humans under propofol','Frontal-parietal, frontal-occipital feedback and frontoparietal connectivity','Frontal-parietal and frontal-occipital feedback directional connectivity declined together with frontoparietal fMRI connectivity.','Simultaneous EEG-fMRI directional connectivity','FALSE','NONE','ND','ND','2','NA','VALIDATED','No score promotion because the finding does not discriminate among top-down theories','GNW, RPT, PP, HOT as rival-compatible top-down mechanisms','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 15.1','NONE','{"import":"v1.1.1","source_table":"15.1 Anesthesia evidence register"}'::jsonb),
('AN-004','SRC-018','ANESTHESIA','Resting EEG with prior TMS-EEG validation','Propofol/xenon versus ketamine','Anesthetic state comparison','Critical dynamics and predicted PCI','Unconscious propofol/xenon states moved away from critical dynamics; ketamine unresponsiveness with vivid experience remained closer to wakefulness and predicted PCI.','Resting EEG + prior TMS-EEG validation','FALSE','NONE','ND','ND','3','NA','VALIDATED','Adds a candidate state constraint, not a new theory-specific confirmation','Cross-theory state marker; integration/dynamical capacity','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 15.1','NONE','{"import":"v1.1.1","source_table":"15.1 Anesthesia evidence register"}'::jsonb),
('AN-005','SRC-019','ANESTHESIA','Model-derived resting-state fMRI metric','Propofol sedation','Humans under propofol','IIT 3.0-inspired Phi-max implementation','An IIT 3.0-inspired Phi-max implementation varied with sedation in some higher-order networks.','Model-derived metric from fMRI','FALSE','NONE','ND','ND','2','NA','VALIDATED','Indirect for IIT 4.0; cannot validate exact intrinsic cause-effect structure','IIT-1 / IIT-4','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 15.1','NONE','{"import":"v1.1.1","source_table":"15.1 Anesthesia evidence register"}'::jsonb),
('AN-006','SRC-020','ANESTHESIA','In vitro substrate assay','Isoflurane/etomidate','Microtubule preparation','Electronic energy migration in microtubules','Anesthetics reduced measured electronic energy migration in microtubules.','In vitro substrate assay','TRUE','SUBSTRATE_MECHANISM_ONLY','ND','ND','0','NA','VALIDATED','Supports anesthetic-sensitive microtubule biophysics only; no consciousness-dependent variable','OR-1 / OR-2 substrate chain','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 15.1','NONE','{"import":"v1.1.1","source_table":"15.1 Anesthesia evidence register"}'::jsonb),

('SL-001','SRC-021','SLEEP','Repeated within-subject report sampling','Serial awakenings across N1/N2/N3/REM','Sleeping humans','Immediate experience reports across sleep stages','Experience reports occurred across sleep stages; sleep consciousness varied in richness, perceptual character and reflectiveness rather than mapping one-to-one onto stage.','Repeated within-subject report sampling','FALSE','NONE','ND','ND','3','NA','VALIDATED','High methodological value; no theory-specific score promotion','Cross-theory dependent-variable control; challenges sleep-stage = consciousness shortcuts','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb),
('SL-002','SRC-022','SLEEP','Within-state EEG plus immediate post-awakening content report','Experience-present versus experience-absent NREM and REM','Sleeping humans','Posterior low-frequency and high-frequency activity with dream reports','Dreaming in both NREM and REM was associated with locally reduced posterior low-frequency activity; posterior high-frequency activity tracked specific reported dream contents.','Within-state EEG + immediate post-awakening content report + prospective prediction','FALSE','NONE','ND','ND','3','NA','VALIDATED','Strong consciousness-sensitive constraint; still correlational','RPT/IIT/content theories; GNWT/HOT constraints; content localization','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb),
('SL-003','SRC-023','SLEEP','Direct perturbation with state contrast','Wake versus NREM TMS-EEG','Sleeping and awake humans','Propagation of TMS-evoked cortical responses','During NREM, TMS evoked a strong local response that rapidly extinguished instead of propagating through connected cortex.','Direct perturbation with state contrast','TRUE','CONSCIOUSNESS_LINKED_SYSTEM','ND','ND','2','NA','VALIDATED','Causal systems constraint, but not experience-sampled trial by trial','IIT/integration; GNWT/global availability; RPT recurrent interaction','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb),
('SL-004','SRC-024','SLEEP','Intracranial perturbation in human NREM','Intracranial stimulation during NREM','Humans in NREM sleep','Slow wave, cortical OFF-period, and cortico-cortical responses','Stimulation triggered a slow wave and cortical OFF-period that disrupted deterministic cortico-cortical responses.','Intracranial perturbation in human NREM','TRUE','CONSCIOUSNESS_LINKED_SYSTEM','ND','ND','2','NA','VALIDATED','Strengthens bistability mechanism; consciousness linkage remains indirect','INT/RPT/GNWT; mechanism for reduced causal interaction','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb),
('SL-005','SRC-025','SLEEP','TMS-EEG perturbation with benchmark subjective reports','Wake, dreaming, NREM, anesthesia, DOC','Cross-state human benchmark conditions','Perturbational Complexity Index','PCI was high in conscious benchmark states including dreaming and lower in conditions classified as unconscious, without requiring contemporaneous behavioral response.','TMS-EEG perturbation + benchmark subjective reports','TRUE','CONSCIOUSNESS_LINKED_SYSTEM','ND','ND','3','NA','VALIDATED','Strong state marker; not exact IIT 4.0 validation','IIT-compatible complexity; cross-theory state capacity','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb),
('SL-006','SRC-026','SLEEP','Independent benchmark validation','Independent PCI validation benchmark','Conscious and unconscious benchmark conditions','PCI cutoff discrimination','A PCI cutoff separated conscious benchmark conditions including dreaming from unconscious benchmark NREM/anesthesia conditions before application to unresponsive patients.','Independent benchmark validation','FALSE','NONE','ND','TRUE','3','NA','VALIDATED','Strengthens consciousness-capacity measure, not phenomenal identity','Cross-theory CMC; IIT-compatible complexity','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb),
('SL-007','SRC-028','SLEEP','Intracranial observational physiology','Human intracranial NREM recordings','Humans in NREM sleep','Spatial distribution of slow waves, spindles, and local activity','Slow waves and spindles were often local rather than globally synchronous, leaving some regions active while others were silent.','Intracranial observational physiology','FALSE','NONE','ND','ND','1','NA','VALIDATED','Shows local sleep-state heterogeneity; consciousness not directly measured','Local-state architecture; RPT/IIT/GNWT constraints','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb),
('SL-008','SRC-027','SLEEP','Review synthesis','2024 synthesis across sleep consciousness literature','Sleep-consciousness literature','Cross-study synthesis of dreaming, bistability, disconnection, and posterior slow-wave activity','Dreaming can be rich while externally disconnected and poorly reflective; dreamless sleep is associated with cortical bistability/disconnection, especially posterior slow-wave activity.','Review synthesis, not new primary experiment','FALSE','NONE','ND','ND','2','NA','VALIDATED','Used to integrate, not independently promote scores','Cross-theory synthesis and experiment design','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 19.1','NONE','{"import":"v1.1.1","source_table":"19.1 Sleep evidence register"}'::jsonb);

COMMIT;
