-- Frozen atomic evidence records from Claim Ledger v1.1.1 Section 24.1.
-- Negative active-test inference is explicitly capped at CMC 1 where applicable.
BEGIN;

INSERT INTO evidence (
 evidence_id,source_id,population_id,design_class,intervention,sample_or_system,
 measured_variable,finding,operational_class,causal_manipulation,preregistered,
 independent_replication,cmc,oec,evidence_status,ledger_score_effect_text,
 ledger_interpretation,ledger_version,source_artifact,source_locator,score_effect,
 asymmetric_inference,negative_inference_cmc_cap,asymmetry_rationale,provenance
) VALUES
('DC-001','SRC-029','DOC_CMD','Repeated structured behavioral assessment','CRS-R validation','Patients with disorders of consciousness','Standardized CRS-R diagnostic performance','Standardized CRS-R showed strong reliability/diagnostic utility for distinguishing levels of consciousness.','Repeated structured behavioral assessment',FALSE,'ND','ND','3','NA','VALIDATED','Behavioral reference standard, not ground truth for phenomenality','Dependent-variable control; all theories','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'Negative CRS-R/no command following detects no overt conscious behavior in that examination; it cannot establish unconsciousness without serial standardized assessment and multimodal follow-up.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb),
('DC-002','SRC-030','DOC_CMD','Standardized neurobehavioral reassessment','Clinical consensus versus standardized CRS-R','Patients labeled vegetative/unresponsive','Behavioral signs consistent with MCS under systematic assessment','A substantial fraction of patients labeled vegetative/unresponsive showed behavioral signs consistent with MCS when systematically assessed.','Standardized neurobehavioral reassessment',FALSE,'ND','ND','3','NA','VALIDATED','Raises prior probability of hidden capacity; does not establish covert consciousness in every negative bedside case','Measurement validity; cross-theory','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'Bedside nonresponse has false-negative potential and is not a consciousness-null test.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb),
('DC-003','SRC-031','DOC_CMD','Active fMRI task-specific within-patient contrast','Tennis and spatial-navigation imagery','Single VS/UWS patient','Task-specific fMRI activation during instructed imagery','Tennis and spatial-navigation imagery produced task-specific activation consistent with command comprehension and intentional cooperation.','Active fMRI, task-specific within-patient contrast',FALSE,'ND','ND','3','NA','VALIDATED','Strong positive evidence of preserved cognition; single-case proof of principle','GNWT/HOT/PP access and volition; consciousness detection','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'A positive task-specific response strongly supports preserved command comprehension and intentional cognitive control; failure to detect one does not establish absence of consciousness.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb),
('DC-004','SRC-032','DOC_CMD','Active fMRI with predefined mental imagery','Mental imagery and scanner communication','54 DoC patients','Willful modulation and yes/no communication','5/54 showed willful modulation; in two no voluntary behavior was found clinically; one patient communicated yes/no in scanner.','Active fMRI with predefined mental imagery',FALSE,'ND','ND','3','NA','VALIDATED','Positive responses strongly constrain bedside-negative diagnoses; low prevalence cannot be read as sensitivity','Access, metacognition, intentional control; measurement validity','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'Low positive prevalence in a demanding active paradigm cannot be interpreted as sensitivity or as evidence that negative patients lack consciousness.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb),
('DC-005','SRC-033','DOC_CMD','Bedside active EEG plus machine learning and longitudinal outcome','EEG command paradigm','104 acutely unresponsive brain-injury patients','Command-related EEG activation and 12-month functional outcome','16/104 (15%) showed command-related EEG activation; CMD-positive patients had better 12-month functional outcomes than CMD-negative patients.','Bedside active EEG + machine learning + longitudinal outcome',FALSE,'ND','ND','3','NA','VALIDATED','Positive response has prognostic/diagnostic value; negative result remains non-decisive','Access, prognosis, causal architecture indirectly','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'Positive active EEG is informative; a negative result is non-decisive because task and signal failures can erase a response.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb),
('DC-006','SRC-034','DOC_CMD','Multicenter multimodal active paradigms plus CRS-R','fMRI/EEG active command paradigms','353 adults across 6 centers','CMD detection versus observable command response','CMD was detected in 60/241 (25%) without observable command response; only 43/112 (38%) behaviorally command-responsive participants were positive on imaging.','Multicenter multimodal active paradigms + CRS-R; observational/volitional, not causal perturbation',FALSE,'ND','ND','3','NA','VALIDATED','Establishes strong positive/negative asymmetry. Positive imaging is informative; negative imaging is not a consciousness-null test. CMC capped at 3 because the study lacks causal manipulation.','Measurement sensitivity; access/report dissociation; all theories','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'The 2024 multicenter cohort directly demonstrates substantial false-negative potential: negative active imaging cannot be equated with absent consciousness.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb),
('DC-007','SRC-035','DOC_CMD','Systematic review and guideline synthesis','AAN/ACRM/NIDILRR guideline','Patients with prolonged disorders of consciousness','Recommended serial assessment and confound management','Serial standardized assessments, treatment of confounds, and optimized arousal are recommended to improve diagnostic accuracy.','Systematic review + guideline synthesis',FALSE,'ND','ND','3','NA','VALIDATED','Promotes repeated multimodal measurement over one-shot classification','Clinical epistemic rules','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'One negative bedside examination is epistemically inadequate for an absence-of-consciousness inference.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb),
('DC-008','SRC-036','DOC_CMD','Methodological review','Analysis of active paradigms','DoC active-paradigm literature','False-positive/false-negative risk and clinical utility uncertainty','Statistical and paradigm choices can produce false positives and false negatives; independent estimates of clinical utility are difficult.','Methodological review',FALSE,'ND','ND','2','NA','VALIDATED','Requires explicit error model; prevents positive/negative symmetry assumptions','Measurement uncertainty; CMC calibration','v1.1.1','Consciousness_Evidence_Map_Claim_Ledger_v1.1.1.docx','Section 24.1','NONE',TRUE,1,'Active-paradigm failures cannot support strong absence claims without independent sensitivity and state-quality validation.','{"import":"v1.1.1","source_table":"24.1 Disorders-of-consciousness evidence register"}'::jsonb);

COMMIT;
