-- Phase 6 scientific-version invariants. Zero rows = pass.
SELECT 'THEORY_VERSION_COUNT' violation,count(*)::text detail FROM theory_versions WHERE specification_version_id='v1.1.1' HAVING count(*)<>8;
SELECT 'CLAIM_VERSION_COUNT' violation,count(*)::text detail FROM claim_versions WHERE specification_version_id='v1.1.1' HAVING count(*)<>27;
SELECT 'CLAIM_VERSION_TEXT_DRIFT' violation,cv.claim_id detail FROM claim_versions cv JOIN claims c USING(claim_id) WHERE cv.specification_version_id='v1.1.1' AND (cv.claim_text IS DISTINCT FROM c.claim_text OR cv.logical_falsifier IS DISTINCT FROM c.logical_falsifier OR cv.operational_test IS DISTINCT FROM c.operational_test OR cv.operational_feasibility IS DISTINCT FROM c.operational_feasibility OR cv.target_relevance_id IS DISTINCT FROM c.target_relevance_id);
SELECT 'THEORY_VERSION_LINK_DRIFT' violation,cv.claim_id detail FROM claim_versions cv JOIN claims c USING(claim_id) JOIN theory_versions tv ON tv.theory_version_id=cv.theory_version_id WHERE cv.specification_version_id='v1.1.1' AND tv.theory_id IS DISTINCT FROM c.theory_id;
SELECT 'CLAIM_TYPE_VERSION_DRIFT' violation,x.claim_id detail FROM (SELECT c.claim_id,array_agg(c.claim_type ORDER BY c.ordinal)::text a,array_agg(v.claim_type ORDER BY v.ordinal)::text b FROM claim_claim_types c FULL JOIN claim_version_types v ON v.claim_version_id='CV-'||c.claim_id||'-v1.1.1' AND v.claim_type=c.claim_type GROUP BY c.claim_id) x WHERE x.a IS DISTINCT FROM x.b;
SELECT 'CLAIM_ROLE_VERSION_DRIFT' violation,c.claim_id detail FROM claims c WHERE (SELECT array_agg(theory_role ORDER BY theory_role)::text FROM claim_theory_roles r WHERE r.claim_id=c.claim_id) IS DISTINCT FROM (SELECT array_agg(theory_role ORDER BY theory_role)::text FROM claim_version_theory_roles r WHERE r.claim_version_id='CV-'||c.claim_id||'-v1.1.1');
SELECT 'NONFROZEN_BASELINE_VERSION' violation,claim_version_id detail FROM claim_versions WHERE specification_version_id='v1.1.1' AND status<>'FROZEN';
SELECT 'IIT_VERSION_LABEL_LOST' violation,theory_version_id detail FROM theory_versions WHERE theory_id='IIT' AND specification_version_id='v1.1.1' AND version_label IS DISTINCT FROM '4.0';
SELECT 'INVENTED_THEORY_VERSION' violation,theory_id detail FROM theory_versions WHERE specification_version_id='v1.1.1' AND theory_id<>'IIT' AND version_label IS NOT NULL;
